### PR TITLE
Working Group GH pages template

### PR DESCRIPTION
**Pull request by gaborcsardi**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@hadley @jmertic @joseph-rickert please take a look

Here is how it looks with one of the builtin GH pages themes: https://gaborcsardi.github.io/wgreadme/

**Comment by jmertic** [comment]
Would you want the LF CS team to build a Jekyll theme to use here? Fairly straightforward for us to do.

**Comment by gaborcsardi** [comment]
I don't mind. We can also see how many groups will actually use it...

**Comment by jmertic** [comment]
Sounds good - adding an LF CS request for this.

**Comment by joseph-rickert** [comment]
Gabor's mock up looks good to me.

Thanks,
Joe

Joseph B. Rickert
RStudio R Community Ambassador
R Consortium Director
Cell: 408.489.0566

**Comment by brianwarner** [comment]
Closing, as this has been open for a while.

**Pull request closed without merging**
